apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ygk8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-rkqf-tenant/e2e-nodejs/devfile-sample-ygk8@sha256:149793609279af7e1e3c160d49d620cf0fd8e4a0f44686bee49e021f03c83408
        name: my-nodejs
        resources: {}
status: {}
